FROM node:18-bookworm as builder

RUN apt-get update && apt-get install -y curl gettext-base jq

WORKDIR /root
COPY ./stacking/stacking.ts ./stacking/package.json ./stacking/common.ts ./stacking/monitor.ts ./stacking/stacking.ts /root/
RUN npm i

CMD ["npx", "tsx", "/root/stacking.ts"]