FROM node:18-bookworm as builder

RUN apt-get update && apt-get install -y curl gettext-base jq

WORKDIR /root
COPY ./stacking/tx-broadcaster.js ./stacking/package.json /root/
RUN npm i

CMD ["node", "/root/tx-broadcaster.js"]